### PR TITLE
Dtedder/390 fix elevation source loading

### LINKED ISSUE #390: Update member pointer to Surface on LocationTextController on change
When a user adds a new data source and uses it for elevation, there is no code to set the m_surface pointer on the LocationTextController tool. The current code only updates this property on GeoView changed which is not triggered by data getting added in this way. As a work around, the location changed event is currently querying to find the baseSurface every time. This should be updated by the SceneQuckView::layerViewStateChanged signal or by a custom signal that can be raised by the AddLocalDataController tool.

### PR DESCRIPTION
**Pull request by dtedder**
fix issue with surface pointer not getting updated if the app is started with an elevation source in the config file that is not valid.

### CODE REVIEW

File: Shared/AddLocalDataController.cpp [hunk 1]
```diff
@@ -238,47 +238,62 @@ void AddLocalDataController::addItemAsElevationSource(const QList<int>& indices)
...
+    if (cache->tileInfo().format() != TileImageFormat::LERC)
+      return;
 
-      auto scene = ToolResourceProvider::instance()->scene();
-      if (scene)
-        scene->baseSurface()->elevationSources()->append(source);
+    // create new elevation source from the tile cache
+    auto* source = new ArcGISTiledElevationSource(cache, this);
+    connect(source, &ArcGISTiledElevationSource::errorOccurred, this, &AddLocalDataController::errorOccurred);
+    connect(source, &ArcGISTiledElevationSource::doneLoading, this, [this, cache, scene, source](const Error& errorSource)
```
Comment (JamesMBallard) [inline Shared/AddLocalDataController.cpp:259]: This is optional, but for connections for things that only happen once (like doneLoading), you can consider a [SingleShotConnection](https://doc.qt.io/qt-6/qt.html#ConnectionType-enum). That will release any resources held by the lambda when it's no longer needed.

I don't think it will cause any issues, but unclear if it's worth changing. Fair warning it's not a pattern we use very often, but I can see it being helpful.

File: Shared/AddLocalDataController.cpp [hunk 2]
```diff
@@ -238,47 +238,62 @@ void AddLocalDataController::addItemAsElevationSource(const QList<int>& indices)
...
+        return;
 
+      scene->baseSurface()->elevationSources()->append(source);
       emit elevationSourceSelected(source);
-      emit propertyChanged(DEFAULT_ELEVATION_PROPERTYNAME, tileCache->path());
-    }
+      emit propertyChanged(DEFAULT_ELEVATION_PROPERTYNAME, cache->path());
+    });
+
+    source->load();
```
Comment (JamesMBallard) [inline Shared/AddLocalDataController.cpp:269]: To be sure I understand the nature of the fix, it is that now we explicitly load the `ArcGISTiledElevationSource`, and only emit `propertyChanged(DEFAULT_ELEVATION_PROPERTYNAME...` once it has completed loading. Does that sound correct?

That way downstream logic can remain unchanged and doesn't need to worry about whether it is loaded or not.

Comment (dtedder) [reply Shared/AddLocalDataController.cpp:269]: Correct. Now the downstream logic in the location changed update can stay what it was before. Just check to make sure `m_surface` pointer is not null. The logic added here will prevent invalid elevation sources from ever being added (which is what was throwing the exceptions).

File: Shared/AddLocalDataController.cpp (hunk 1 above)
Comment (dtedder) [reply Shared/AddLocalDataController.cpp:259]: I'll take a look at this. Sounds useful for cases like these.

Comment (JamesMBallard) [reply Shared/AddLocalDataController.cpp:259]: On second thought I think we should not use it. There could be too many gotchas where we might guess wrong about a signal that only emits once. It's harder to reason about than I realized.

**Review by JamesMBallard — APPROVED** [review]

**Comment by dtedder** [comment]
previous PR (#437), closed in favor of this approach
